import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually

  tutorialSidebar: [
    'hardware/doc-intro',
    'hardware/product-overview',
    'hardware/safety',
    'hardware/quick-start',
    {
      type: 'category',
      collapsed: false,
      label: 'Know Your Micro Storage System',
      items: [
        'hardware/overview/product-models',
        'hardware/overview/system-overview',
        'hardware/overview/appearance-interface'
      ],
    },
    {
      type: 'category',
      collapsed: false,
      label: 'Daily Use',
      items: [
        'hardware/basic/power-on-off',
        'hardware/basic/status-data',
      ],
    },
    {
      type: 'category',
      collapsed: false,
      label: 'Energy Management',
      link: {type: 'doc', id: 'hardware/energy-mode/energy-mode'},
      items: [
        'hardware/energy-mode/self-consumption',
        'hardware/energy-mode/charge-discharge-schedule',
        'hardware/energy-mode/real-time-control',
        'hardware/energy-mode/price-strategy',
      ],
    },
    {
      type: 'category',
      collapsed: false,
      label: 'Advanced Settings',
      items: [
        'hardware/advanced/link-device',
        'hardware/advanced/accessory-replacement',
        'hardware/advanced/third-party-inverter',
        'hardware/advanced/third-party-inverter-dual-metering',
        'hardware/advanced/three-phase-meter',
      ],
    },
    {
      type: 'category',
      collapsed: false,
      label: 'Technical Note',
      items: [
        'hardware/technical-note/standby-power',
        'hardware/technical-note/recharge',
        'hardware/technical-note/energy-calibration',
        'hardware/technical-note/lora',
        'hardware/technical-note/thermal-derating',
        'hardware/technical-note/bypass',
        'hardware/technical-note/device-communication',
        'hardware/technical-note/soc-balancing',
        'hardware/technical-note/cluster',
      ],
    },
    {
      type: 'category',
      collapsed: false,
      label: 'OpenData',
      items: [
        'hardware/open-data/introduction',
        {
          type: 'category',
          label: 'HTTP/HTTPS',
          items: [
            'hardware/open-data/http',
            'hardware/open-data/http-api',
          ],
        },
        {
          type: 'category',
          label: 'Modbus',
          items: [
            'hardware/open-data/modbus',
            'hardware/open-data/modbus-register-table',
          ],
        },
        {
          type: 'category',
          label: 'MQTT',
          items: [
            'hardware/open-data/mqtt',
            'hardware/open-data/mqtt-topic',
          ],
        },
        'hardware/open-data/home-assistant',
      ],
    },
    {
      type: 'category',
      label: 'Technical Specification',
      items: [
        'hardware/tech-specs/power-tech-specs',
        'hardware/tech-specs/battery-tech-specs',
      ],
    },
    'hardware/faq-troubleshooting',
    'hardware/maintenance',
    'hardware/glossary',
    'hardware/firmware',
    'hardware/doc-version'
  ],
  appSidebar: [
    'app/introduction',
    'app/release-notes',
    {
      type: 'category',
      label: 'Getting Started',
      collapsed: false,
      link: {
        type: 'generated-index',
        title: 'Getting Started',
        description:
          "Get started with INDEVOLT by installing the app, creating your account, and setting up your first device.",
      },
      items: [
        'app/installation',
        'app/registration-login',
        'app/add-device'
      ],
    },
    {
      type: 'category',
      label: 'Using INDEVOLT',
      collapsed: false,
      link: {
        type: 'generated-index',
        title: 'Using INDEVOLT',
        description:
          "This section walks through key functions, from energy monitoring to personal settings."
      },
      items: [
        'app/home',
        'app/report',
        'app/smart',
        'app/device',
        'app/profile',
        {
          type: 'category',
          label: 'Brand Connection',
          collapsed: false,
          link: {
            type: 'generated-index',
            title: 'Brand Connection',
            description: `
            Connect your home energy devices to supported brands. On the Profile page, tap Brand Connection, select the brand you want to connect, and follow the corresponding guide below to obtain the required API credentials or other authorization information.
            `,
          },
          items: [
            'app/goodwe',
            'app/growatt',
            'app/solaredge',
            'app/solax',
            'app/sungrow',
          ],
        },
      ],
    },
    'app/faq'
  ]

};

export default sidebars;
