import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually

  tutorialSidebar: [
    // 'hardware/doc-intro',
    // 'hardware/product-overview',
    // 'hardware/safety',
    // 'hardware/quick-start',
    // {
    //   type: 'category',
    //   collapsed: false,
    //   label: 'Know Your Micro Storage System',
    //   items: [
    //     'hardware/overview/product-models',
    //     'hardware/overview/system-overview',
    //     'hardware/overview/appearance-interface'
    //   ],
    // },
    // {
    //   type: 'category',
    //   collapsed: false,
    //   label: 'Daily Use',
    //   items: [
    //     'hardware/basic/power-on-off',
    //     'hardware/basic/status-data',
    //   ],
    // },
    // {
    //   type: 'category',
    //   collapsed: false,
    //   label: 'Energy Management',
    //   items: [
    //     'hardware/advanced/self-consumption',
    //     'hardware/advanced/charge-discharge-schedule',
    //     'hardware/advanced/real-time-control',
    //     'hardware/advanced/price-strategy',
    //   ],
    // },
    // {
    //   type: 'category',
    //   collapsed: false,
    //   label: 'Technical Information & Capabilities',
    //   items: [
    //     {
    //       type: 'category',
    //       collapsed: false,
    //       label: 'Technical Specification',
    //       items: [
    //         'hardware/geek/power-tech-specs',
    //         'hardware/geek/battery-tech-specs',
    //       ],
    //     },
    //     'hardware/geek/open-data',
    //     'hardware/geek/home-assistant',
    //     'hardware/geek/device-integration'
    //   ],
    // },
    // 'hardware/faq-troubleshooting',
    // 'hardware/after-sales',
    // 'hardware/maintenance',
    // 'hardware/compliance',
    // 'hardware/glossary',
    // 'hardware/firmware'
  ],
  appSidebar: [
    'app/introduction',
    'app/release-notes',
    {
      type: 'category',
      label: 'Getting Started',
      collapsed: false,
      link: {
        type: 'generated-index',
        title: 'Getting Started',
        description:
          "Get started with INDEVOLT by installing the app, creating your account, and setting up your first device.",
      },
      items: [
        'app/installation',
        'app/registration-login',
        'app/add-device'
      ],
    },
    {
      type: 'category',
      label: 'Using INDEVOLT',
      collapsed: false,
      link: {
        type: 'generated-index',
        title: 'Using INDEVOLT',
        description:
          "This section walks through key functions, from energy monitoring to personal settings."
      },
      items: [
        'app/home',
        'app/report',
        'app/smart',
        'app/device',
        'app/profile'
      ],
    },
    'app/faq'
  ]

};

export default sidebars;
